---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-flux-nginx
  namespace: test-managementzones
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: test-managementzones
      interval: 1m
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      service:
        type: ClusterIP
      ingressClassResource:
        default: false
