---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-flux-nginx
  namespace: test-managementzones
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: ">=0.15.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: test-managementzones
      interval: 1m
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      service:
        type: ClusterIP
